SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY,
    SUM(SALES * PRICE) AS TOTAL_SALES
FROM BOOK_SALES
    JOIN BOOK USING(BOOK_ID)
    JOIN AUTHOR USING(AUTHOR_ID)
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC