WITH RECURSIVE GENS AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT e.ID, e.PARENT_ID, GENS.GENERATION + 1 AS GENERATION
    FROM GENS
        JOIN ECOLI_DATA e ON e.PARENT_ID = GENS.ID
)

SELECT ID
FROM GENS
WHERE GENERATION = 3
ORDER BY ID