WITH CTE AS (
    SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR AS C
        JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
        ON C.CAR_ID = H.CAR_ID
    WHERE C.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01' # 11월 1일부터 11월 30일 까지 대여할 수 없는 조건
    ) AND
    C.CAR_TYPE IN ('세단', 'SUV')
),
CTE2 AS (
    SELECT DISTINCT A.CAR_ID, A.CAR_TYPE, 
        ROUND((A.DAILY_FEE * ((100 - P.DISCOUNT_RATE) / 100)) * 30) AS FEE
    FROM CTE AS A
        JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
        ON A.CAR_TYPE = P.CAR_TYPE
    WHERE P.DURATION_TYPE = '30일 이상'
)

SELECT *
FROM CTE2
WHERE FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC