WITH AVAILABLE_CAR AS (
    SELECT CAR_ID, CAR_TYPE, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR C
    WHERE CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= '2022-11-30'
            AND END_DATE >= '2022-11-01'
    )
), THIRTY_FEE AS (
    SELECT A.CAR_ID, P.CAR_TYPE, (A.DAILY_FEE * ((100 - P.DISCOUNT_RATE) / 100) * 30) AS 'FEE'
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
        JOIN AVAILABLE_CAR A ON P.CAR_TYPE = A.CAR_TYPE
    WHERE P.CAR_TYPE IN ('세단', 'SUV')
        AND P.DURATION_TYPE LIKE '30일%'
)

SELECT CAR_ID, CAR_TYPE, FEE
FROM THIRTY_FEE
WHERE FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC