WITH FILTERED_USER AS (
    SELECT WRITER_ID
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING COUNT(BOARD_ID) >= 3
)

SELECT USER_ID, NICKNAME,
    CONCAT_WS(' ', CITY, STREET_ADDRESS1, STREET_ADDRESS2) AS '전체주소',
    CONCAT_WS('-', SUBSTR(TLNO, 1, 3), SUBSTR(TLNO, 4, 4), SUBSTR(TLNO, 8, 4)) AS '전화번호'
FROM USED_GOODS_USER
    JOIN FILTERED_USER
    ON USER_ID = WRITER_ID
ORDER BY USER_ID DESC