WITH WRITERS AS (
    SELECT WRITER_ID
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING COUNT(*) >= 3
)

SELECT U.USER_ID, NICKNAME,
    CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS '전체주소',
    CONCAT_WS('-', SUBSTR(TLNO, 1, 3), SUBSTR(TLNO, 4, 4), SUBSTR(TLNO, -4, 4)) AS '전화번호'
FROM WRITERS W JOIN USED_GOODS_USER U ON W.WRITER_ID = U.USER_ID
ORDER BY U.USER_ID DESC