SELECT I.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME
FROM ANIMAL_INS I
    JOIN ANIMAL_OUTS O
    ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE SUBSTRING_INDEX(I.SEX_UPON_INTAKE, ' ', 1) = 'Intact' and SUBSTRING_INDEX(O.SEX_UPON_OUTCOME, ' ', 1) IN ('Spayed', 'Neutered')