SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER, COUNT(DISTINCT S.USER_ID) AS USERS
FROM ONLINE_SALE S
    JOIN USER_INFO U
    ON S.USER_ID = U.USER_ID AND GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY 1, 2, 3
;