WITH RENT_DATE AS (
    SELECT CAR_ID, TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1 AS RENT_DATE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)

SELECT CAR_ID, ROUND(AVG(RENT_DATE), 1) AS AVERAGE_DURATION
FROM RENT_DATE
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC