WITH TARGET_USER AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
), TARGET_DATA AS (
    SELECT S.*
    FROM ONLINE_SALE S
        JOIN TARGET_USER T ON S.USER_ID = T.USER_ID
)

SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH,
    COUNT(DISTINCT USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT USER_ID) / (SELECT COUNT(*) FROM TARGET_USER), 1) AS PUCHASED_RATIO
FROM TARGET_DATA
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR, MONTH