WITH RECURSIVE GEN AS (
    SELECT ID, PARENT_ID, 1 AS 'GENERATION'
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT e.ID, e.PARENT_ID, g.GENERATION + 1 AS 'GENERATION'
    FROM GEN g
        JOIN ECOLI_DATA e
        ON e.PARENT_ID = g.ID
)

SELECT COUNT(*) AS COUNT,
    GENERATION
FROM GEN g
    LEFT JOIN (
        SELECT DISTINCT PARENT_ID
        FROM GEN
    ) AS p
    ON g.ID = p.PARENT_ID
WHERE p.PARENT_ID IS NULL
GROUP BY GENERATION
ORDER BY GENERATION

