SELECT CONCAT(Q, 'Q') AS QUARTER, COUNT(*) AS ECOLI_COUNT
FROM (SELECT ID,
    CASE
        WHEN MONTH(DIFFERENTIATION_DATE) IN (1, 2, 3) THEN 1
        WHEN MONTH(DIFFERENTIATION_DATE) IN (4, 5, 6) THEN 2
        WHEN MONTH(DIFFERENTIATION_DATE) IN (7, 8, 9) THEN 3
        ELSE 4
    END AS Q
FROM ECOLI_DATA) Q_DATA
GROUP BY Q
ORDER BY Q