SELECT HISTORY_ID,
       ROUND(DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1) * (100 - IFNULL(DISCOUNT_RATE, 0)) / 100, 0) AS FEE
FROM (
    SELECT *,
        CASE
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 7 THEN NULL
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 30 THEN '7일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 90 THEN '30일 이상'
            ELSE '90일 이상'
        END DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) a
JOIN CAR_RENTAL_COMPANY_CAR b
ON a.CAR_ID = b.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN c
ON c.CAR_TYPE = b.CAR_TYPE AND a.DURATION_TYPE = c.DURATION_TYPE
WHERE b.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC