WITH RECURSIVE CTE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT CTE.HOUR + 1 AS HOUR
    FROM CTE
    WHERE HOUR < 23
)

SELECT CTE.HOUR,
    CASE 
        WHEN A.ANIMAL_ID IS NOT NULL THEN COUNT(*)
        ELSE 0
    END
    AS COUNT
FROM CTE
    LEFT JOIN ANIMAL_OUTS A ON CTE.HOUR = HOUR(A.DATETIME)
GROUP BY CTE.HOUR
ORDER BY CTE.HOUR