WITH REVIEW_CNT AS (
    SELECT MEMBER_ID, COUNT(REVIEW_ID) AS CNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
), REVIEWER_RANK AS (
    SELECT MEMBER_ID, DENSE_RANK() OVER (ORDER BY CNT DESC) AS RANKS
    FROM REVIEW_CNT
)

SELECT P.MEMBER_NAME, RR.REVIEW_TEXT, 
    DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REVIEWER_RANK R
    JOIN MEMBER_PROFILE P ON R.MEMBER_ID = P.MEMBER_ID
    JOIN REST_REVIEW RR ON R.MEMBER_ID = RR.MEMBER_ID
WHERE RANKS = 1
ORDER BY RR.REVIEW_DATE, RR.REVIEW_TEXT