WITH MAX_COLONY AS (
    SELECT ID, SIZE_OF_COLONY AS 'SIZE',
        YEAR(DIFFERENTIATION_DATE) AS 'YEAR',
        MAX(SIZE_OF_COLONY) OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE)) AS 'MAX_COLONY_SIZE'
    FROM ECOLI_DATA
)

SELECT YEAR,
    MAX_COLONY_SIZE - SIZE AS 'YEAR_DEV',
    ID
FROM MAX_COLONY
ORDER BY YEAR, YEAR_DEV