SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO I
    JOIN (
        SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
        FROM FISH_INFO
        GROUP BY FISH_TYPE
    ) L USING(FISH_TYPE) 
    JOIN FISH_NAME_INFO N USING(FISH_TYPE)
WHERE I.LENGTH = L.MAX_LENGTH
ORDER BY ID