SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO
    JOIN (
            SELECT FISH_TYPE, MAX(LENGTH) AS M_LENGTH
            FROM FISH_INFO
            GROUP BY FISH_TYPE
        ) AS M_INFO
    ON FISH_INFO.FISH_TYPE = M_INFO.FISH_TYPE AND FISH_INFO.LENGTH = M_INFO.M_LENGTH
    JOIN FISH_NAME_INFO ON FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
ORDER BY ID