WITH TOTAL_SCORE AS (
    SELECT EMP_NO, SUM(SCORE) AS 'SCORE'
    FROM HR_GRADE
    GROUP BY EMP_NO
)

SELECT S.SCORE, E.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES E
    JOIN (
        SELECT EMP_NO,
            SCORE,
            DENSE_RANK() OVER (ORDER BY SCORE DESC) AS 'RANK'
        FROM TOTAL_SCORE
    ) AS S
    ON E.EMP_NO = S.EMP_NO
WHERE S.RANK = 1
